"""alters stamp_templates adds status column


Revision ID: 0a5d79652a04
Revises: 698d135736b4
Create Date: 2025-04-03 13:26:42.744132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a5d79652a04'
down_revision = '698d135736b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stamp_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
                'status', 
                postgresql.ENUM('ACT', 'INACT', 'SUSP', 'ARCH', 'FLG', name='status', create_type=False),
                default='ACT',
                nullable=False
            )
        )

    with op.batch_alter_table('stamps', schema=None) as batch_op:
        batch_op.alter_column('template_content',
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=sa.JSON(),
            existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stamps', schema=None) as batch_op:
        batch_op.alter_column('template_content',
            existing_type=sa.JSON(),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=False)

    with op.batch_alter_table('stamp_templates', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
