"""empty message

Revision ID: 13201e6aa9ec
Revises: e943b4459278
Create Date: 2025-03-27 23:24:41.708620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13201e6aa9ec'
down_revision = 'e943b4459278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_payments',
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('currency', postgresql.ENUM('USD', 'EUR', 'GBP', 'KES', name='currency', create_type=False), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('organisation_subscription_id', sa.String(), nullable=False),
    sa.Column('payment_method', sa.Enum('BANK', 'CARD', 'APPLE_PAY', 'GOOGLE_PAY', 'PAYPAL', 'MOMO', name='paymentmethod'), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=45), nullable=False),
    sa.Column('status', postgresql.ENUM('ACT', 'INACT', 'SUSP', 'ARCH', 'FLG', name='status', create_type=False), nullable=False),
    sa.Column('status_description', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['organisation_subscription_id'], ['organisation_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_customer_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('paystack_customer_id')

    op.drop_table('subscription_payments')
    # ### end Alembic commands ###
