"""Adds doc_url column to documents table

Revision ID: 43e99c8415bc
Revises: f8a7b57142b1
Create Date: 2025-05-19 15:48:16.978580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e99c8415bc'
down_revision = 'f8a7b57142b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
