"""empty message

Revision ID: 587687c7c4b1
Revises: 
Create Date: 2025-03-18 12:36:31.221245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587687c7c4b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('RETAIL', 'TELECOM', 'AGRICULTURE', 'REAL_ESTATE', 'HOSPITALITY', 'TECH', 'BEAUTY', 'HEALTHCARE', 'FOOD_AND_BEVERAGE', 'FASHION', 'ACCOUNTING_AND_FINANCE', 'LEGAL', 'ENTERTAINMENT', 'GENERAL', name='businesscategory'), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('google_organisation_id', sa.String(length=30), nullable=True),
    sa.Column('website_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_organisation_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('first_name', sa.String(length=15), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(length=15), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SYS_ADM', 'OWN', 'ADM', 'USR', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACT', 'INACT', 'SUSP', 'ARCH', 'FLG', name='status'), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('organisations')
    # ### end Alembic commands ###
