"""drops subscriptions_payments status col

Revision ID: 65579936333d
Revises: 13201e6aa9ec
Create Date: 2025-04-02 20:47:05.754186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65579936333d'
down_revision = '13201e6aa9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('ACT', 'INACT', 'SUSP', 'ARCH', 'FLG', name='status'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
