"""updates stamp_template_metadata

Revision ID: 82356e8dc4ca
Revises: b6a74c8bd2b6
Create Date: 2025-04-09 13:18:52.958129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82356e8dc4ca'
down_revision = 'b6a74c8bd2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stamp_template_metadata', schema=None) as batch_op:
        batch_op.drop_constraint('stamp_template_metadata_template_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'stamp_templates', ['template_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stamp_template_metadata', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stamp_template_metadata_template_id_fkey', 'stamp_templates', ['template_id'], ['id'])

    # ### end Alembic commands ###
