"""Updates stamp tables and adds stamp_applications table

Revision ID: b6a74c8bd2b6
Revises: 0a5d79652a04
Create Date: 2025-04-08 17:18:18.368118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a74c8bd2b6'
down_revision = '0a5d79652a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stamp_applications',
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('stamp_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['stamp_id'], ['stamps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stamp_audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stamp_application_id', sa.String(), nullable=True))
        batch_op.alter_column('stamp_id',
            existing_type=sa.VARCHAR(),
            nullable=True)
        batch_op.create_foreign_key(None, 'stamp_applications', ['stamp_application_id'], ['id'])

    with op.batch_alter_table('stamp_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))

    with op.batch_alter_table('stamps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stamps', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('stamp_templates', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('stamp_audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('stamp_id',
            existing_type=sa.VARCHAR(),
            nullable=False)
        batch_op.drop_column('stamp_application_id')

    op.drop_table('stamp_applications')
    # ### end Alembic commands ###
