"""alters stamp_template_metadata table; adds type column

Revision ID: cb1b1f3db18a
Revises: 82356e8dc4ca
Create Date: 2025-04-09 20:44:50.190157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1b1f3db18a'
down_revision = '82356e8dc4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stamp_template_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), default='TEXT'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stamp_template_metadata', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
