"""adds new subscriptions_payments status col

Revision ID: e38601fd2416
Revises: 65579936333d
Create Date: 2025-04-02 20:48:09.454263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e38601fd2416'
down_revision = '65579936333d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        payment_status = postgresql.ENUM('COMP', 'INIT', 'PEND', 'FAIL', 'FLG', 'CANC', name='payment_status', create_type=False)
        payment_status.create(op.get_bind(), checkfirst=True)
        batch_op.add_column(sa.Column('status', payment_status, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
