"""adds subscription_plans & organisations_subscriptions

Revision ID: e943b4459278
Revises: 587687c7c4b1
Create Date: 2025-03-22 00:46:50.678247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e943b4459278'
down_revision = '587687c7c4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', name='currency'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('features', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('period_in_days', sa.Integer(), nullable=False),
    sa.Column('plan_url', sa.String(length=180), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('provider_plan_id', sa.String(length=45), nullable=False),
    sa.Column('service_provider', sa.Enum('PAYSTACK', name='service_provider'), nullable=False),
    sa.Column('status', postgresql.ENUM('ACT', 'INACT', 'SUSP', 'ARCH', 'FLG', name='status', create_type=False), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organisation_subscriptions',
    sa.Column('canceled_on', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('currency', postgresql.ENUM('USD', 'EUR', 'GBP', name='currency', create_type=False), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('next_billing_on', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=45), nullable=False),
    sa.Column('subscription_customer_id', sa.String(length=45), nullable=False),
    sa.Column('subscription_plan_id', sa.String(), nullable=True),
    sa.Column('status', postgresql.ENUM('ACT', 'INACT', 'SUSP', 'ARCH', 'FLG', name='status', create_type=False), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_subscription_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.alter_column('created_on',
              existing_type=postgresql.TIMESTAMP(),
              type_=sa.TIMESTAMP(timezone=True),
              existing_nullable=False)
        batch_op.alter_column('updated_on',
              existing_type=postgresql.TIMESTAMP(),
              type_=sa.TIMESTAMP(timezone=True),
              existing_nullable=False)
        batch_op.create_unique_constraint(None, ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_on',
              existing_type=sa.TIMESTAMP(timezone=True),
              type_=postgresql.TIMESTAMP(),
              existing_nullable=False)
        batch_op.alter_column('created_on',
              existing_type=sa.TIMESTAMP(timezone=True),
              type_=postgresql.TIMESTAMP(),
              existing_nullable=False)
        batch_op.drop_column('phone_number')
        batch_op.drop_column('country_code')

    op.drop_table('organisation_subscriptions')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
